In [ ]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [ ]:
cd drive/MyDrive/EvaluationTSE

/content/drive/MyDrive/EvaluationTSE

In [ ]:
####!git clone https://github.com/tech-srl/code2vec #

In [ ]:
cd code2vec

/content/drive/MyDrive/EvaluationTSE/code2vec

In [ ]:
with open('badcode.java','r', encoding='utf-8') as firstfile, open('Input.java','w', encoding='utf-8') as secondfile:
  for i,line in enumerate(firstfile):
    secondfile.write(line)

FileNotFoundError: ignored

In [ ]:
with open('goodcode.java','r', encoding='utf-8') as firstfile, open('Input.java','w', encoding='utf-8') as secondfile:
  for i,line in enumerate(firstfile):
    secondfile.write(line)

In [ ]:
#!wget https://s3.amazonaws.com/code2vec/model/java14m_model.tar.gz

In [ ]:
#!tar -xvzf java14m_model.tar.gz #

In [ ]:
!rm  code_vector_results.txt

In [ ]:
!python code2vec.py --load models/java14_model/saved_model_iter8.release --predict --export_code_vectors

2022-08-15 23:09:20.901847: E tensorflow/stream_executor/cuda/cuda_driver.cc:271] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
2022-08-15 23:09:20,907 INFO
2022-08-15 23:09:20,907 INFO
2022-08-15 23:09:20,907 INFO     ---------------------------------------------------------------------
2022-08-15 23:09:20,908 INFO     ---------------------------------------------------------------------
2022-08-15 23:09:20,908 INFO     ---------------------- Creating code2vec model ----------------------
2022-08-15 23:09:20,908 INFO     ---------------------------------------------------------------------
2022-08-15 23:09:20,908 INFO     ---------------------------------------------------------------------
2022-08-15 23:09:20,908 INFO     Checking number of examples ...
2022-08-15 23:09:20,908 INFO     ---------------------------------------------------------------------
2022-08-15 23:09:20,908 INFO     ----------------- Configuration - Hyper Parameters ------------------
2022-08-15 23:09:20,908 INFO     CODE_VECTOR_SIZE                          384
2022-08-15 23:09:20,908 INFO     CSV_BUFFER_SIZE                           104857600
2022-08-15 23:09:20,908 INFO     DEFAULT_EMBEDDINGS_SIZE                   128
2022-08-15 23:09:20,908 INFO     DL_FRAMEWORK                              tensorflow
2022-08-15 23:09:20,908 INFO     DROPOUT_KEEP_RATE                         0.75
2022-08-15 23:09:20,908 INFO     EXPORT_CODE_VECTORS                       True
2022-08-15 23:09:20,908 INFO     LOGS_PATH                                 None
2022-08-15 23:09:20,909 INFO     MAX_CONTEXTS                              200
2022-08-15 23:09:20,909 INFO     MAX_PATH_VOCAB_SIZE                       911417
2022-08-15 23:09:20,909 INFO     MAX_TARGET_VOCAB_SIZE                     261245
2022-08-15 23:09:20,909 INFO     MAX_TOKEN_VOCAB_SIZE                      1301136
2022-08-15 23:09:20,909 INFO     MAX_TO_KEEP                               10
2022-08-15 23:09:20,909 INFO     MODEL_LOAD_PATH                           models/java14_model/saved_model_iter8.release
2022-08-15 23:09:20,909 INFO     MODEL_SAVE_PATH                           None
2022-08-15 23:09:20,909 INFO     NUM_BATCHES_TO_LOG_PROGRESS               100
2022-08-15 23:09:20,909 INFO     NUM_TEST_EXAMPLES                         0
2022-08-15 23:09:20,909 INFO     NUM_TRAIN_BATCHES_TO_EVALUATE             1800
2022-08-15 23:09:20,909 INFO     NUM_TRAIN_EPOCHS                          20
2022-08-15 23:09:20,909 INFO     NUM_TRAIN_EXAMPLES                        0
2022-08-15 23:09:20,909 INFO     PATH_EMBEDDINGS_SIZE                      128
2022-08-15 23:09:20,909 INFO     PREDICT                                   True
2022-08-15 23:09:20,909 INFO     READER_NUM_PARALLEL_BATCHES               6
2022-08-15 23:09:20,909 INFO     RELEASE                                   False
2022-08-15 23:09:20,909 INFO     SAVE_EVERY_EPOCHS                         1
2022-08-15 23:09:20,909 INFO     SAVE_T2V                                  None
2022-08-15 23:09:20,909 INFO     SAVE_W2V                                  None
2022-08-15 23:09:20,909 INFO     SEPARATE_OOV_AND_PAD                      False
2022-08-15 23:09:20,910 INFO     SHUFFLE_BUFFER_SIZE                       10000
2022-08-15 23:09:20,910 INFO     TARGET_EMBEDDINGS_SIZE                    384
2022-08-15 23:09:20,910 INFO     TEST_BATCH_SIZE                           1024
2022-08-15 23:09:20,910 INFO     TEST_DATA_PATH
2022-08-15 23:09:20,910 INFO     TOKEN_EMBEDDINGS_SIZE                     128
2022-08-15 23:09:20,910 INFO     TOP_K_WORDS_CONSIDERED_DURING_PREDICTION  10
2022-08-15 23:09:20,910 INFO     TRAIN_BATCH_SIZE                          1024
2022-08-15 23:09:20,910 INFO     TRAIN_DATA_PATH_PREFIX                    None
2022-08-15 23:09:20,910 INFO     USE_TENSORBOARD                           False
2022-08-15 23:09:20,910 INFO     VERBOSE_MODE                              1
2022-08-15 23:09:20,910 INFO     _Config__logger                           <Logger code2vec (INFO)>
2022-08-15 23:09:20,910 INFO     context_vector_size                       384
2022-08-15 23:09:20,910 INFO     entire_model_load_path                    models/java14_model/saved_model_iter8.release__entire-model
2022-08-15 23:09:20,910 INFO     entire_model_save_path                    None
2022-08-15 23:09:20,910 INFO     is_loading                                True
2022-08-15 23:09:20,910 INFO     is_saving                                 False
2022-08-15 23:09:20,910 INFO     is_testing                                False
2022-08-15 23:09:20,910 INFO     is_training                               False
2022-08-15 23:09:20,910 INFO     model_load_dir                            models/java14_model
2022-08-15 23:09:20,910 INFO     model_weights_load_path                   models/java14_model/saved_model_iter8.release__only-weights
2022-08-15 23:09:20,911 INFO     model_weights_save_path                   None
2022-08-15 23:09:20,911 INFO     test_steps                                0
2022-08-15 23:09:20,911 INFO     train_data_path                           None
2022-08-15 23:09:20,911 INFO     train_steps_per_epoch                     0
2022-08-15 23:09:20,911 INFO     word_freq_dict_path                       None
2022-08-15 23:09:20,911 INFO     ---------------------------------------------------------------------
2022-08-15 23:09:21,190 INFO     Loading model vocabularies from: `models/java14_model/dictionaries.bin` ...
2022-08-15 23:09:25,618 INFO     Done loading model vocabularies.
2022-08-15 23:09:26,392 INFO     Done creating code2vec model
2022-08-15 23:09:50,547 INFO     Initalized variables
2022-08-15 23:09:50,559 INFO     Loading model weights from: models/java14_model/saved_model_iter8.release
2022-08-15 23:10:11,420 INFO     Done loading model weights
Starting interactive prediction...
Modify the file: "Input.java" and press any key when ready, or "q" / "quit" / "exit" to exit

Modify the file: "Input.java" and press any key when ready, or "q" / "quit" / "exit" to exit
q
Exiting...

In [ ]:
with open('code_vector_results.txt','r') as firstfile, open('code_vector_results_Dataset_Bad.txt','w') as secondfile:
    for line in firstfile:
             secondfile.write(line)

In [ ]:
import pandas as pd

vectors_table_Bad = pd.read_csv('code_vector_results_Dataset_Bad.txt', sep=" ", header=None)

In [ ]:
vectors_table_Bad.shape

(609, 384)

In [ ]:
vectors_table_Bad

In [ ]:
with open('code_vector_results.txt','r') as firstfile, open('code_vector_results_Dataset_Good.txt','w') as secondfile:
    for line in firstfile:
             secondfile.write(line)

In [ ]:
import pandas as pd

vectors_table_Good = pd.read_csv('code_vector_results_Dataset_Good.txt', sep=" ", header=None)

In [ ]:
vectors_table_Good.shape

In [ ]:
vectors_table_Good

In [ ]:
import pandas as pd

vectors_table_Merged = pd.read_csv('uniqueAll.txt', sep=" ", header=None)

In [ ]:
from scipy import spatial
results = list()
vectors_table.detach
for i in range(0,len(vectors_table)):
  result = 1 - spatial.distance.cosine(vectors_table_oracle[i], vectors_table[i])
  results.append(result)

In [ ]:
results

In [ ]:
from scipy import spatial
#results = list()
f= open('outputEmbedding.txt','w')
f.write("\n")
for i in range(0,len(vectors_table_Merged)):
  temp = list()
  for j in range(0,len(vectors_table_Merged)):
    resultOne = 1 - spatial.distance.cosine(vectors_table_Merged.iloc[i].tolist(), vectors_table_Merged.iloc[j].tolist())
    temp.append(resultOne)
    f.write(str(resultOne)+" ")
    #f.write("samiha")
  f.write("\n")
f.write("\n")
  #results.append(temp)
f.close()

NameError: ignored

In [ ]:
import pandas as pd
  
# read text file into pandas DataFrame
df = pd.read_csv("outputEmbedding.txt", sep=" ", header=None)
  
# display DataFrame
print(df.shape)

(893, 894)

In [ ]:
import pandas as pd
  
# read text file into pandas DataFrame
df = pd.read_excel("Similarity_Matrix.xlsx", header=None)
  
# display DataFrame
print(df.shape)

(893, 893)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,883,884,885,886,887,888,889,890,891,892
0,1.000000,0.569298,0.462255,0.151984,0.211741,0.252946,0.102729,0.138980,0.271752,0.250555,...,0.282715,0.186827,0.197257,0.253537,0.210226,0.204609,0.106996,0.120684,0.474219,0.256029
1,0.569298,1.000000,0.426693,0.174099,0.134236,0.148094,0.195297,0.044825,0.289058,0.276201,...,0.252097,0.184758,0.160665,0.240550,0.223706,0.196448,0.171976,0.172091,0.402762,0.143002
2,0.462255,0.426693,1.000000,0.318643,0.098820,0.229890,0.158988,0.077337,0.404932,0.196575,...,0.387796,0.340887,0.335718,0.228000,0.279224,0.245535,0.157654,0.151975,0.503510,0.299272
3,0.151984,0.174099,0.318643,1.000000,0.255163,0.376266,0.264805,0.034673,0.340200,0.233164,...,0.286751,0.209466,0.256235,0.326018,0.158212,0.188021,0.125086,0.163414,0.164702,0.208028
4,0.211741,0.134236,0.098820,0.255163,1.000000,0.084418,0.157127,0.152673,0.321301,0.283157,...,0.100967,0.187942,0.224605,0.151285,0.111577,0.171912,0.104976,0.158984,0.103945,0.243710
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,0.204609,0.196448,0.245535,0.188021,0.171912,0.168626,0.163144,0.212014,0.230486,0.319293,...,0.486169,0.726868,0.811213,0.268331,0.939055,1.000000,0.791634,0.859155,0.340106,0.140317
889,0.106996,0.171976,0.157654,0.125086,0.104976,0.180394,0.251489,0.205137,0.191762,0.256758,...,0.313867,0.603823,0.553364,0.301581,0.848654,0.791634,1.000000,0.942297,0.255481,0.118958
890,0.120684,0.172091,0.151975,0.163414,0.158984,0.176441,0.231252,0.218489,0.208417,0.258629,...,0.317444,0.544986,0.608168,0.278973,0.809825,0.859155,0.942297,1.000000,0.282766,0.129460
891,0.474219,0.402762,0.503510,0.164702,0.103945,0.393673,0.168895,0.133441,0.334812,0.247858,...,0.274830,0.223078,0.258127,0.336743,0.331970,0.340106,0.255481,0.282766,1.000000,0.251206
892,0.256029,0.143002,0.299272,0.208028,0.243710,0.237967,0.155414,0.190404,0.237799,0.265363,...,0.265710,0.198989,0.185238,0.182780,0.144676,0.140317,0.118958,0.129460,0.251206,1.000000

In [ ]:
df.drop(df.columns[[893]], axis=1, inplace=True)

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,883,884,885,886,887,888,889,890,891,892
0,1.000000,0.709178,0.070864,0.118744,-0.013360,-0.019059,0.111275,-0.107446,-0.041477,0.095196,...,0.023165,0.135315,-0.019025,-0.047278,-0.015723,-0.081479,0.032276,-0.110045,0.091639,-0.040494
1,0.709178,1.000000,-0.039471,0.087609,-0.100654,-0.046081,0.093388,-0.144978,0.152844,0.041514,...,-0.041504,0.085530,-0.048766,-0.053071,-0.064390,-0.051610,0.001387,0.032166,0.006132,-0.019651
2,0.070864,-0.039471,1.000000,0.077736,-0.019510,0.056292,-0.004917,-0.113766,0.015004,0.062778,...,0.193870,0.124920,0.046379,0.028678,0.215804,0.086758,0.071637,-0.107597,0.069317,0.016166
3,0.118744,0.087609,0.077736,1.000000,0.171751,-0.034807,0.102009,-0.069441,0.028612,0.146173,...,-0.098905,-0.160340,-0.119727,-0.054998,-0.199918,-0.135347,0.070215,0.207374,-0.000565,0.093476
4,-0.013360,-0.100654,-0.019510,0.171751,1.000000,-0.028570,0.158675,0.126804,-0.132268,0.120839,...,0.014014,-0.039375,0.013467,-0.064666,-0.059471,-0.052820,-0.012364,-0.003719,-0.108192,-0.089959
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,-0.081479,-0.051610,0.086758,-0.135347,-0.052820,0.141421,-0.067493,0.011818,-0.124161,-0.016636,...,0.361395,0.434863,0.689678,-0.157149,0.668813,1.000000,-0.015020,0.106550,-0.011019,-0.029315
889,0.032276,0.001387,0.071637,0.070215,-0.012364,-0.147554,0.035574,-0.054448,-0.210127,-0.044875,...,-0.037168,0.059679,0.090793,0.032895,0.284964,-0.015020,1.000000,0.490557,0.021166,-0.085001
890,-0.110045,0.032166,-0.107597,0.207374,-0.003719,-0.037554,-0.111975,-0.012812,-0.089358,-0.045183,...,-0.148060,-0.013301,-0.070540,-0.063440,-0.152296,0.106550,0.490557,1.000000,0.077607,-0.051273
891,0.091639,0.006132,0.069317,-0.000565,-0.108192,0.206861,-0.131013,-0.179012,0.046261,-0.035634,...,0.000931,0.115043,-0.157251,-0.059870,0.007051,-0.011019,0.021166,0.077607,1.000000,0.072909
892,-0.040494,-0.019651,0.016166,0.093476,-0.089959,0.033674,-0.015912,0.017082,0.177427,-0.020352,...,0.026093,-0.030484,-0.052185,-0.047404,-0.045403,-0.029315,-0.085001,-0.051273,0.072909,1.000000

In [ ]:
listBadGood = list()
for i in range(0,284):
  listBadGood.append("Bad")

for i in range(0,609):
  listBadGood.append("Good")
print(len(listBadGood))

893

In [ ]:
listIndex = list()
for i in range(0,893):
  listIndex.append(i)

In [ ]:
df['GroundTruth'] = listBadGood

In [ ]:
df['Index'] = listIndex

In [ ]:
df

,0,1,2,3,4,5,6,7,8,9,...,885,886,887,888,889,890,891,892,GroundTruth,Index
0,1.000000,0.709178,0.070864,0.118744,-0.013360,-0.019059,0.111275,-0.107446,-0.041477,0.095196,...,-0.019025,-0.047278,-0.015723,-0.081479,0.032276,-0.110045,0.091639,-0.040494,Bad,0
1,0.709178,1.000000,-0.039471,0.087609,-0.100654,-0.046081,0.093388,-0.144978,0.152844,0.041514,...,-0.048766,-0.053071,-0.064390,-0.051610,0.001387,0.032166,0.006132,-0.019651,Bad,1
2,0.070864,-0.039471,1.000000,0.077736,-0.019510,0.056292,-0.004917,-0.113766,0.015004,0.062778,...,0.046379,0.028678,0.215804,0.086758,0.071637,-0.107597,0.069317,0.016166,Bad,2
3,0.118744,0.087609,0.077736,1.000000,0.171751,-0.034807,0.102009,-0.069441,0.028612,0.146173,...,-0.119727,-0.054998,-0.199918,-0.135347,0.070215,0.207374,-0.000565,0.093476,Bad,3
4,-0.013360,-0.100654,-0.019510,0.171751,1.000000,-0.028570,0.158675,0.126804,-0.132268,0.120839,...,0.013467,-0.064666,-0.059471,-0.052820,-0.012364,-0.003719,-0.108192,-0.089959,Bad,4
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,-0.081479,-0.051610,0.086758,-0.135347,-0.052820,0.141421,-0.067493,0.011818,-0.124161,-0.016636,...,0.689678,-0.157149,0.668813,1.000000,-0.015020,0.106550,-0.011019,-0.029315,Good,888
889,0.032276,0.001387,0.071637,0.070215,-0.012364,-0.147554,0.035574,-0.054448,-0.210127,-0.044875,...,0.090793,0.032895,0.284964,-0.015020,1.000000,0.490557,0.021166,-0.085001,Good,889
890,-0.110045,0.032166,-0.107597,0.207374,-0.003719,-0.037554,-0.111975,-0.012812,-0.089358,-0.045183,...,-0.070540,-0.063440,-0.152296,0.106550,0.490557,1.000000,0.077607,-0.051273,Good,890
891,0.091639,0.006132,0.069317,-0.000565,-0.108192,0.206861,-0.131013,-0.179012,0.046261,-0.035634,...,-0.157251,-0.059870,0.007051,-0.011019,0.021166,0.077607,1.000000,0.072909,Good,891
892,-0.040494,-0.019651,0.016166,0.093476,-0.089959,0.033674,-0.015912,0.017082,0.177427,-0.020352,...,-0.052185,-0.047404,-0.045403,-0.029315,-0.085001,-0.051273,0.072909,1.000000,Good,892

In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test=train_test_split(df,test_size=0.2)

In [ ]:
x_train

,0,1,2,3,4,5,6,7,8,9,...,885,886,887,888,889,890,891,892,GroundTruth,Index
478,0.327476,0.235066,0.069980,-0.019299,-0.017642,-0.077739,0.012160,-0.052890,0.009628,0.041627,...,-0.070670,-0.162696,-0.052628,-0.010646,-0.120875,-0.094784,-0.083514,0.196884,Good,478
217,0.181609,0.038345,0.165585,0.077336,0.159692,-0.032370,-0.013917,-0.135933,-0.008664,0.040801,...,-0.132549,-0.048198,-0.110175,-0.084368,0.002018,0.007161,-0.104729,-0.048025,Bad,217
680,0.252429,0.316554,-0.033788,0.035745,-0.163686,0.029539,0.088652,-0.081708,0.045730,0.211297,...,0.022498,0.072398,-0.025736,-0.040162,0.044983,0.115689,-0.037586,0.003637,Good,680
128,0.003057,-0.058517,0.127758,-0.198344,-0.076676,0.192666,0.000238,0.182654,-0.121377,0.076662,...,0.184816,0.087900,0.140933,0.158346,-0.068250,-0.127243,-0.019924,0.138288,Bad,128
874,-0.061495,0.086104,0.077389,0.152720,-0.120251,0.089607,-0.064923,-0.123823,0.154307,0.125355,...,0.001455,0.202504,-0.099540,-0.014781,-0.086068,0.105695,0.106160,0.336918,Good,874
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
661,0.001884,0.037612,0.061821,-0.029128,-0.036451,0.067469,-0.164063,0.012378,0.089077,0.040476,...,-0.085465,0.088606,-0.087864,-0.074837,-0.209452,-0.083363,0.062119,0.057464,Good,661
640,-0.056922,-0.024986,0.136251,-0.042139,-0.025184,0.084866,0.045463,0.004079,0.063666,0.086967,...,0.434120,0.045787,0.443298,0.383818,0.001959,-0.104950,0.050985,0.025355,Good,640
397,0.195337,0.024284,0.601253,0.075993,0.026602,0.073513,0.015775,-0.125429,-0.043956,0.059298,...,-0.003520,0.034229,0.114956,0.094911,-0.023922,-0.084661,0.140577,0.019006,Good,397
510,-0.000901,0.046748,0.058386,-0.100941,0.032276,-0.145155,0.244224,0.061056,-0.057895,-0.032679,...,0.158033,0.134757,0.183285,0.019175,0.184960,-0.053328,-0.174696,-0.127327,Good,510
161,0.272253,0.301751,-0.100276,-0.166297,-0.024396,0.066826,0.198272,0.098759,-0.019364,0.004254,...,0.034237,0.135488,-0.013804,-0.003269,-0.029441,-0.135963,-0.080606,-0.126717,Bad,161

In [ ]:
x_train.iloc[478].tolist()

In [ ]:

f = open("topResult.txt","w")
ls = x_train.values.tolist()
print(ls[0])
temp = list()
for i in range(0,893):
  temp.append(ls[0][i])

res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-6:]
item = ls[0][894]
#print(item)
#res.remove(item)
print("Indices list of max N elements is : " + str(res))
temp2 = list()
for i in range(0,len(res)):

  #temp2.append(temp[res[i]])
  #temp2.sort(reverse=True)
  print(temp[res[i]])
  print(ls[res[i]][893])
  f.write(str(temp[res[i]])+" ")
  
#print(temp2)
f.close()

NameError: ignored

In [ ]:
f = open("topResult.txt","w")
ls = df.values.tolist()

for j in range(0,893):
  #print(j)
  #print(ls[j])
  temp = list()
  for i in range(0,893):
    temp.append(ls[j][i])
  temp3= temp
  res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-6:]
  
  #print("Indices list of max N elements is : " + str(res))
  if (j) in res:
    res.remove(j)
  else:
    #print("here")
    res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-5:]
  #print(res)
  #item = ls[0][894]
  #print(item)
  #res.remove(item)
  #print("Indices list of max N elements is : " + str(res))
  temp2 = list()
  f.write(str(ls[j][894])+" "+str(ls[j][893])+" ")
  temp3 = list()
  for i in range(0,len(res)):
    temp4 = list()
    #print(temp[res[i]])
    #print(res[i])
    temp4.append(temp[res[i]])
    temp4.append(res[i])
    temp3.append(temp4)
  new_data = sorted(temp3, key=lambda row: (row[0]), reverse=True)
  #print("sorted")
  #print(new_data)
  res2=list()
  for i in range(0,len(new_data)):
    #print(new_data[i][1])
    res2.append(new_data[i][1])
  #print("res2")
  #print(res2)
  for i in range(0,len(res2)):
    '''
    print(ls[j][894])
    print(ls[j][893])
    print(temp[res[i]])
    print(res[i])
    print(ls[res[i]][893])
    '''
    f.write(str(temp[res2[i]])+" "+str(res2[i])+" "+str(ls[res2[i]][893])+" ")
    temp2.append(ls[res2[i]][893])
    #print(temp3)
  #print(temp2)
  badCount = temp2.count('Bad')
  goodCount = temp2.count('Good')
  f.write(str(badCount)+" "+ str(goodCount) +" ")
  resultFound = str()
  if badCount>goodCount:
    resultFound = 'Bad'
  else:
    resultFound ="Good"
  f.write(str(resultFound))
  f.write("\n")
#print(temp2)

f.close()

In [ ]:
import pandas as pd
  
# read text file into pandas DataFrame
df3 = pd.read_csv("topResult.txt", sep=" ", header=None)
  
# display DataFrame
print(df3.shape)

(893, 20)

In [ ]:
df3

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19
0,0,Bad,0.969017,43,Bad,0.966470,387,Good,0.709178,1,Bad,0.660475,284,Good,0.509991,73,Bad,3,2,Bad
1,1,Bad,0.970029,284,Good,0.709178,0,Bad,0.698019,43,Bad,0.686024,387,Good,0.379888,73,Bad,3,2,Bad
2,2,Bad,0.980038,287,Good,0.728915,394,Good,0.724223,49,Bad,0.615234,52,Bad,0.614983,50,Bad,3,2,Bad
3,3,Bad,0.440868,493,Good,0.384471,381,Good,0.342343,767,Good,0.305561,415,Good,0.292767,443,Good,0,5,Good
4,4,Bad,0.972417,288,Good,0.277508,132,Bad,0.264417,402,Good,0.246595,440,Good,0.244147,512,Good,1,4,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,888,Good,0.689678,631,Good,0.689678,885,Good,0.668813,887,Good,0.517762,134,Bad,0.483477,633,Good,1,4,Good
889,889,Good,0.636072,630,Good,0.531721,513,Good,0.506561,133,Bad,0.490557,890,Good,0.476883,135,Bad,2,3,Good
890,890,Good,0.564710,630,Good,0.490557,889,Good,0.442396,108,Bad,0.440349,318,Good,0.436795,652,Good,1,4,Good
891,891,Good,0.319589,375,Good,0.316419,807,Good,0.279765,40,Bad,0.265273,176,Bad,0.265200,808,Good,2,3,Good
892,892,Good,0.960269,280,Bad,0.336918,874,Good,0.322426,592,Good,0.321625,591,Good,0.312082,595,Good,1,4,Good

In [ ]:
listGood =list()
listBad = list()

for i in range(0,893):
  bad =0
  good =0
  tList= df3.iloc[i].tolist()
  print(tList)
  if tList[4] == 'Bad':
    bad += 5*tList[2]
  else:
    good += 5*tList[2]

  if tList[7] == 'Bad':
    bad += 4*tList[5]
  else:
    good += 4*tList[5]

  if tList[10] == 'Bad':
    bad += 3*tList[8]
  else:
    good += 3*tList[8]
  '''
  if tList[13] == 'Bad':
    bad += 2*tList[11]
  else:
    good += 2*tList[11]

  if tList[16] == 'Bad':
    bad += 1*tList[14]
  else:
    good += 1*tList[14]
  '''
  listGood.append(good)
  listBad.append(bad)
  print(good)
  print(bad)

In [ ]:
df3[20]=listGood
df3[21] = listBad

In [ ]:
df3

,0,1,2,3,4,5,6,7,8,9,...,12,13,14,15,16,17,18,19,20,21
0,0,Bad,0.969017,43,Bad,0.966470,387,Good,0.709178,1,...,284,Good,0.509991,73,Bad,3,2,Bad,3.865879,6.972620
1,1,Bad,0.970029,284,Good,0.709178,0,Bad,0.698019,43,...,387,Good,0.379888,73,Bad,3,2,Bad,4.850146,4.930769
2,2,Bad,0.980038,287,Good,0.728915,394,Good,0.724223,49,...,52,Bad,0.614983,50,Bad,3,2,Bad,7.815852,2.172670
3,3,Bad,0.440868,493,Good,0.384471,381,Good,0.342343,767,...,415,Good,0.292767,443,Good,0,5,Good,4.769252,0.000000
4,4,Bad,0.972417,288,Good,0.277508,132,Bad,0.264417,402,...,440,Good,0.244147,512,Good,1,4,Good,5.655339,1.110033
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
888,888,Good,0.689678,631,Good,0.689678,885,Good,0.668813,887,...,134,Bad,0.483477,633,Good,1,4,Good,8.213544,0.000000
889,889,Good,0.636072,630,Good,0.531721,513,Good,0.506561,133,...,890,Good,0.476883,135,Bad,2,3,Good,5.307240,1.519684
890,890,Good,0.564710,630,Good,0.490557,889,Good,0.442396,108,...,318,Good,0.436795,652,Good,1,4,Good,4.785777,1.327189
891,891,Good,0.319589,375,Good,0.316419,807,Good,0.279765,40,...,176,Bad,0.265200,808,Good,2,3,Good,2.863620,0.839295
892,892,Good,0.960269,280,Bad,0.336918,874,Good,0.322426,592,...,591,Good,0.312082,595,Good,1,4,Good,2.314950,4.801345

In [ ]:
data = [[12, 'Good'],
        [ 10, 'Bad'],
        [ 13, 'Good']]

new_data = sorted(data, key=lambda row: (row[0]), reverse=True)

print(new_data)

[[13, 'Good'], [12, 'Good'], [10, 'Bad']]

In [ ]:
df3.to_excel("result.xlsx")

In [ ]:
df3.drop(df.columns[[19]], axis=1, inplace=True)

In [ ]:
len(x_test)

179

In [ ]:
import pandas as pd
  
# read text file into pandas DataFrame
#df2  =pd.read_excel('bad_code_.xlsx', index_col=0, header=None) 
df2 = pd.read_excel (r'bad_code.xlsx')
#print (df) 
  
# display DataFrame
#print(df2.iloc[:,[0]])
#frames = [df, df2]
#result = pd.concat(frames)

In [ ]:
print(df2.iloc[:,[0,1]])

In [ ]:
#print(df2.iloc[:,:1])
df.insert(loc=0, column="Stars", value=df2.iloc[:,[0]])
#df.insert(loc=1, column="Stars2", value=df2.iloc[:,[1]])
df.to_excel("output.xlsx")

In [ ]:
df.loc[:, "Year"] = df2.iloc[:,[0]]

In [ ]:
df.to_excel("output.xlsx")

In [ ]:
df.loc[:, "Year2"] = df2.iloc[:,[1]]

In [ ]:
df.insert(loc=2, column="Stars2", value=df2.iloc[:,[1])

In [ ]:
result.iloc[0].tolist()

In [ ]:
print(result)

In [ ]:
f= open(r'/content/drive/MyDrive/EvaluationTSE/code2vec/outputEmbedding.txt','w')
f.write("samihssa")
f.close()

In [ ]:
from scipy import spatial
#results = list()
f= open('outputEmbedding.txt','w')
f.write("\n")

1

In [ ]:
# part 2

In [ ]:
# generating cosine similarity for bad code only

In [ ]:
import pandas as pd

vectors_table_Merged = pd.read_csv('uniqueBadEmbeddings.txt', sep=" ", header=None)

In [ ]:
import pandas as pd

vectors_table_Merged = pd.read_excel('Commit_Messages_Similarity_Matrix.xlsx', header=None)

In [ ]:
import pandas as pd

vectors_table_Merged = pd.read_excel('Bad_Code_Similarity_Matrix.xlsx', header=None)

In [ ]:
vectors_table_Merged

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.321122,-0.534529,0.462216,0.716275,-0.206658,0.355301,-0.359482,0.249406,-0.592634,0.399595,...,-0.150393,-0.256804,0.548393,-0.039623,0.212820,0.497672,0.462663,-0.432214,0.361658,0.790811
1,-0.679095,0.423418,-0.106932,0.721652,0.516845,0.350763,-0.192788,0.594786,-0.039124,0.198786,...,0.469896,-0.234735,0.646336,-0.064931,0.586109,0.682179,-0.033398,-0.250343,0.639206,0.799550
2,-0.676910,0.213696,-0.076179,-0.353702,-0.896898,-0.328535,0.351178,-0.200673,-0.020420,0.543329,...,-0.001248,-0.079478,-0.100063,0.250145,0.031357,-0.267373,-0.151884,0.405906,0.345005,-0.071316
3,-0.470763,-0.706792,-0.688844,0.728950,0.047468,0.317607,0.368588,-0.319263,-0.079970,-0.001865,...,-0.313115,0.583079,0.045874,-0.347156,-0.263069,-0.108744,-0.174398,0.367448,0.460573,0.434728
4,-0.127342,-0.445793,-0.345440,-0.132351,0.024425,0.024260,0.080114,-0.678628,-0.120985,0.573767,...,-0.294851,0.485232,0.045195,-0.302013,0.004885,0.476545,-0.107532,0.503138,0.229798,0.844376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,-0.333047,-0.475630,-0.789792,-0.032266,-0.276664,0.096351,-0.305177,-0.955842,0.512784,0.407968,...,-0.018101,0.621096,-0.017547,-0.832465,-0.113139,0.486798,0.285192,-0.692648,0.005897,-0.303013
280,-0.051658,-0.004847,-0.148456,0.012711,0.246357,0.142224,-0.340888,-0.198262,-0.325692,0.388964,...,-0.129903,-0.000789,0.173083,0.486542,-0.301261,-0.275480,0.134571,-0.445049,-0.293472,-0.392823
281,-0.326300,0.084798,0.205341,-0.111315,0.706837,0.176517,-0.429406,0.565463,-0.828929,0.495750,...,-0.633981,-0.668414,0.367966,-0.704300,0.432363,0.857986,0.764011,-0.576278,0.037884,0.742000
282,0.858271,0.320726,-0.982753,-0.284050,0.892211,0.227396,-0.022624,0.584316,-0.439349,-0.173000,...,-0.287429,-0.698324,-0.055437,-0.621741,-0.029827,0.550825,0.545367,-0.529979,-0.028878,0.016206
283,0.960884,0.374988,-0.990768,-0.338348,0.766587,0.103964,-0.298782,0.630900,-0.190704,0.106729,...,-0.361754,-0.733875,-0.138018,-0.659537,0.246272,0.184958,0.163763,-0.531567,-0.119504,0.068847

In [ ]:
from scipy import spatial
#results = list()
f= open('outputEmbeddingBad.txt','w')
f.write("\n")
for i in range(0,len(vectors_table_Merged)):
  temp = list()
  for j in range(0,len(vectors_table_Merged)):
    resultOne = 1 - spatial.distance.cosine(vectors_table_Merged.iloc[i].tolist(), vectors_table_Merged.iloc[j].tolist())
    temp.append(resultOne)
    f.write(str(resultOne)+" ")
    #f.write("samiha")
  f.write("\n")
f.write("\n")
  #results.append(temp)
f.close()

In [ ]:
import pandas as pd
# read text file into pandas DataFrame
df5 = pd.read_csv("outputEmbeddingBad.txt", sep=" ", header=None)
  
# display DataFrame
print(df5.shape)

(284, 285)

In [ ]:
df5

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,1.000000,0.709178,0.070864,0.118744,-0.013360,-0.019059,0.111275,-0.107446,-0.041477,0.095196,...,0.019365,-0.066549,0.169465,-0.020326,0.121121,-0.046839,0.110150,-0.040098,-0.068451,NaN
1,0.709178,1.000000,-0.039471,0.087609,-0.100654,-0.046081,0.093388,-0.144978,0.152844,0.041514,...,-0.032337,-0.035243,0.186745,-0.022874,0.127571,-0.042706,0.011295,-0.023612,-0.059084,NaN
2,0.070864,-0.039471,1.000000,0.077736,-0.019510,0.056292,-0.004917,-0.113766,0.015004,0.062778,...,-0.041858,-0.058733,-0.093861,0.194819,-0.016895,-0.022551,-0.146463,-0.130881,-0.094567,NaN
3,0.118744,0.087609,0.077736,1.000000,0.171751,-0.034807,0.102009,-0.069441,0.028612,0.146173,...,0.105679,-0.030671,0.095887,-0.101721,0.162760,0.073215,-0.072193,0.025464,-0.007862,NaN
4,-0.013360,-0.100654,-0.019510,0.171751,1.000000,-0.028570,0.158675,0.126804,-0.132268,0.120839,...,0.067897,-0.027567,0.113940,0.025788,-0.029934,-0.096949,0.097498,-0.009174,0.010254,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.121121,0.127571,-0.016895,0.162760,-0.029934,0.144460,-0.024949,-0.068237,0.177266,0.096782,...,-0.029400,0.011068,-0.103386,0.102266,1.000000,0.077143,-0.034381,0.216226,0.244515,NaN
280,-0.046839,-0.042706,-0.022551,0.073215,-0.096949,0.068649,0.004147,0.033878,0.192880,0.003415,...,0.047993,0.143690,-0.080040,0.088877,0.077143,1.000000,0.155176,0.043487,-0.012525,NaN
281,0.110150,0.011295,-0.146463,-0.072193,0.097498,-0.043268,0.098712,0.334914,-0.029856,0.073129,...,0.020055,0.243549,0.095307,0.061690,-0.034381,0.155176,1.000000,0.374063,0.346804,NaN
282,-0.040098,-0.023612,-0.130881,0.025464,-0.009174,0.053090,-0.131854,0.097557,0.130340,-0.029080,...,0.079408,0.178943,0.105504,0.045247,0.216226,0.043487,0.374063,1.000000,0.900648,NaN
283,-0.068451,-0.059084,-0.094567,-0.007862,0.010254,0.043785,-0.113580,0.050910,0.146082,0.037965,...,0.089582,0.237807,0.107466,0.059552,0.244515,-0.012525,0.346804,0.900648,1.000000,NaN

In [ ]:
df5.drop(df5.columns[[284]], axis=1, inplace=True)

In [ ]:
vectors_table_Merged

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.321122,-0.534529,0.462216,0.716275,-0.206658,0.355301,-0.359482,0.249406,-0.592634,0.399595,...,-0.150393,-0.256804,0.548393,-0.039623,0.212820,0.497672,0.462663,-0.432214,0.361658,0.790811
1,-0.679095,0.423418,-0.106932,0.721652,0.516845,0.350763,-0.192788,0.594786,-0.039124,0.198786,...,0.469896,-0.234735,0.646336,-0.064931,0.586109,0.682179,-0.033398,-0.250343,0.639206,0.799550
2,-0.676910,0.213696,-0.076179,-0.353702,-0.896898,-0.328535,0.351178,-0.200673,-0.020420,0.543329,...,-0.001248,-0.079478,-0.100063,0.250145,0.031357,-0.267373,-0.151884,0.405906,0.345005,-0.071316
3,-0.470763,-0.706792,-0.688844,0.728950,0.047468,0.317607,0.368588,-0.319263,-0.079970,-0.001865,...,-0.313115,0.583079,0.045874,-0.347156,-0.263069,-0.108744,-0.174398,0.367448,0.460573,0.434728
4,-0.127342,-0.445793,-0.345440,-0.132351,0.024425,0.024260,0.080114,-0.678628,-0.120985,0.573767,...,-0.294851,0.485232,0.045195,-0.302013,0.004885,0.476545,-0.107532,0.503138,0.229798,0.844376
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,-0.333047,-0.475630,-0.789792,-0.032266,-0.276664,0.096351,-0.305177,-0.955842,0.512784,0.407968,...,-0.018101,0.621096,-0.017547,-0.832465,-0.113139,0.486798,0.285192,-0.692648,0.005897,-0.303013
280,-0.051658,-0.004847,-0.148456,0.012711,0.246357,0.142224,-0.340888,-0.198262,-0.325692,0.388964,...,-0.129903,-0.000789,0.173083,0.486542,-0.301261,-0.275480,0.134571,-0.445049,-0.293472,-0.392823
281,-0.326300,0.084798,0.205341,-0.111315,0.706837,0.176517,-0.429406,0.565463,-0.828929,0.495750,...,-0.633981,-0.668414,0.367966,-0.704300,0.432363,0.857986,0.764011,-0.576278,0.037884,0.742000
282,0.858271,0.320726,-0.982753,-0.284050,0.892211,0.227396,-0.022624,0.584316,-0.439349,-0.173000,...,-0.287429,-0.698324,-0.055437,-0.621741,-0.029827,0.550825,0.545367,-0.529979,-0.028878,0.016206
283,0.960884,0.374988,-0.990768,-0.338348,0.766587,0.103964,-0.298782,0.630900,-0.190704,0.106729,...,-0.361754,-0.733875,-0.138018,-0.659537,0.246272,0.184958,0.163763,-0.531567,-0.119504,0.068847

In [ ]:
# read text file into pandas DataFrame
import pandas as pd
df6 = pd.read_excel("bad_code_unique.xlsx",header=None)
  
# display DataFrame
print(df6[1])

0       CWE-79
1       CWE-79
2       CWE-79
3      CWE-327
4      CWE-327
        ...
279    CWE-862
280    CWE-732
281    CWE-732
282    CWE-732
283    CWE-732
Name: 1, Length: 284, dtype: object

In [ ]:
listCWE = df6[1]

In [ ]:
df5[284]=listCWE

In [ ]:
df5

,0,1,2,3,4,5,6,7,8,9,...,275,276,277,278,279,280,281,282,283,284
0,1.000000,0.709178,0.070864,0.118744,-0.013360,-0.019059,0.111275,-0.107446,-0.041477,0.095196,...,0.019365,-0.066549,0.169465,-0.020326,0.121121,-0.046839,0.110150,-0.040098,-0.068451,CWE-79
1,0.709178,1.000000,-0.039471,0.087609,-0.100654,-0.046081,0.093388,-0.144978,0.152844,0.041514,...,-0.032337,-0.035243,0.186745,-0.022874,0.127571,-0.042706,0.011295,-0.023612,-0.059084,CWE-79
2,0.070864,-0.039471,1.000000,0.077736,-0.019510,0.056292,-0.004917,-0.113766,0.015004,0.062778,...,-0.041858,-0.058733,-0.093861,0.194819,-0.016895,-0.022551,-0.146463,-0.130881,-0.094567,CWE-79
3,0.118744,0.087609,0.077736,1.000000,0.171751,-0.034807,0.102009,-0.069441,0.028612,0.146173,...,0.105679,-0.030671,0.095887,-0.101721,0.162760,0.073215,-0.072193,0.025464,-0.007862,CWE-327
4,-0.013360,-0.100654,-0.019510,0.171751,1.000000,-0.028570,0.158675,0.126804,-0.132268,0.120839,...,0.067897,-0.027567,0.113940,0.025788,-0.029934,-0.096949,0.097498,-0.009174,0.010254,CWE-327
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,0.121121,0.127571,-0.016895,0.162760,-0.029934,0.144460,-0.024949,-0.068237,0.177266,0.096782,...,-0.029400,0.011068,-0.103386,0.102266,1.000000,0.077143,-0.034381,0.216226,0.244515,CWE-862
280,-0.046839,-0.042706,-0.022551,0.073215,-0.096949,0.068649,0.004147,0.033878,0.192880,0.003415,...,0.047993,0.143690,-0.080040,0.088877,0.077143,1.000000,0.155176,0.043487,-0.012525,CWE-732
281,0.110150,0.011295,-0.146463,-0.072193,0.097498,-0.043268,0.098712,0.334914,-0.029856,0.073129,...,0.020055,0.243549,0.095307,0.061690,-0.034381,0.155176,1.000000,0.374063,0.346804,CWE-732
282,-0.040098,-0.023612,-0.130881,0.025464,-0.009174,0.053090,-0.131854,0.097557,0.130340,-0.029080,...,0.079408,0.178943,0.105504,0.045247,0.216226,0.043487,0.374063,1.000000,0.900648,CWE-732
283,-0.068451,-0.059084,-0.094567,-0.007862,0.010254,0.043785,-0.113580,0.050910,0.146082,0.037965,...,0.089582,0.237807,0.107466,0.059552,0.244515,-0.012525,0.346804,0.900648,1.000000,CWE-732

In [ ]:
listIndex = list()
for i in range(0,284):
  listIndex.append(i)

In [ ]:
df5[285]=listIndex

In [ ]:
f = open("topResultBad.txt","w")
ls = df5.values.tolist()

for j in range(0,284):
  #print(j)
  #print(ls[j])
  temp = list()
  for i in range(0,284):
    temp.append(ls[j][i])
  temp3= temp
  res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-6:]
  
  print("Indices list of max N elements is : " + str(res))
  if (j) in res:
    res.remove(j)
  else:
    #print("here")
    res = sorted(range(len(temp)), key = lambda sub: temp[sub])[-5:]
  #print(res)
  #item = ls[0][894]
  #print(item)
  #res.remove(item)
  #print("Indices list of max N elements is : " + str(res))
  temp2 = list()
  f.write(str(ls[j][285])+" "+str(ls[j][284])+" ")
  temp3 = list()
  for i in range(0,len(res)):
    temp4 = list()
    #print(temp[res[i]])
    #print(res[i])
    temp4.append(temp[res[i]])
    temp4.append(res[i])
    temp3.append(temp4)
  new_data = sorted(temp3, key=lambda row: (row[0]), reverse=True)
  #print("sorted")
  #print(new_data)
  res2=list()
  for i in range(0,len(new_data)):
    #print(new_data[i][1])
    res2.append(new_data[i][1])
  #print("res2")
  #print(res2)
  for i in range(0,len(res2)):
    '''
    print(ls[j][894])
    print(ls[j][893])
    print(temp[res[i]])
    print(res[i])
    print(ls[res[i]][893])
    '''
    f.write(str(temp[res2[i]])+" "+str(res2[i])+" "+str(ls[res2[i]][284])+" ")
    temp2.append(ls[res2[i]][284])
    #print(temp3)
  #print(temp2)
  '''
  badCount = temp2.count('Bad')
  goodCount = temp2.count('Good')
  f.write(str(badCount)+" "+ str(goodCount) +" ")
  resultFound = str()
  if badCount>goodCount:
    resultFound = 'Bad'
  else:
    resultFound ="Good"
  f.write(str(resultFound))
  '''
  f.write("\n")
  
#print(temp2)

f.close()

In [ ]:
import pandas as pd
  
# read text file into pandas DataFrame
df6 = pd.read_csv("topResultBad.txt", sep=" ", header=None)
  
# display DataFrame
print(df6.shape)

(284, 18)

In [ ]:
df6

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17
0,0,CWE-79,0.969017,43,CWE-352,0.709178,1,CWE-79,0.509991,73,CWE-22,0.423585,106,CWE-89,0.409600,42,CWE-287,NaN
1,1,CWE-79,0.709178,0,CWE-79,0.698019,43,CWE-352,0.379888,73,CWE-22,0.355555,175,CWE-20,0.345969,106,CWE-89,NaN
2,2,CWE-79,0.724223,49,CWE-352,0.615234,52,CWE-352,0.614983,50,CWE-352,0.359971,205,CWE-732,0.359971,212,CWE-732,NaN
3,3,CWE-327,0.211456,248,CWE-78,0.206611,143,CWE-502,0.205309,62,CWE-362,0.201631,78,CWE-22,0.198746,172,CWE-428,NaN
4,4,CWE-327,0.277508,132,CWE-91,0.241131,131,CWE-91,0.229998,133,CWE-91,0.226984,47,CWE-352,0.210698,83,CWE-20,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,279,CWE-862,0.288656,62,CWE-362,0.275619,90,CWE-347,0.260459,41,CWE-74,0.250460,248,CWE-78,0.244515,283,CWE-732,NaN
280,280,CWE-732,0.319783,171,CWE-379,0.256628,167,CWE-379,0.250705,168,CWE-379,0.246808,172,CWE-428,0.246433,40,CWE-352,NaN
281,281,CWE-732,0.374063,282,CWE-732,0.346804,283,CWE-732,0.334914,7,CWE-502,0.322559,255,CWE-346,0.312118,265,CWE-22,NaN
282,282,CWE-732,0.900648,283,CWE-732,0.374063,281,CWE-732,0.253221,255,CWE-346,0.217107,75,CWE-502,0.216226,279,CWE-862,NaN
283,283,CWE-732,0.900648,282,CWE-732,0.346804,281,CWE-732,0.253576,255,CWE-346,0.244515,279,CWE-862,0.237807,276,CWE-22,NaN

In [ ]:
listCWE79 =list()
listCWE327 = list()
listCWE502 = list()
listCWE91 = list()
listCWE22 = list()
listCWE835 = list()
listCWE20 = list()
listCWE74 = list()
listCWE200 = list()
listCWE94 = list()
listCWE611 = list()
listCWE352 = list()
listCWE287 = list()
listCWE362 = list()
listCWE190 = list()
listCWE755 = list()
listCWE347 = list()
listCWE338 = list()
listCWE770 = list()
listCWE284 = list()
listCWE798 = list()
listCWE89 = list()
listCWE434 = list()
listCWE538 = list()
listCWE759 = list()
listCWE379 = list()
listCWE428 = list()
listCWE863 = list()
listCWE915 = list()
listCWE203 = list()
listCWE732 = list()
listCWE326 = list()
listCWE269 = list()
listCWE119 = list()
listCWE918 = list()
listCWE295 = list()
listCWE78 = list()
listCWE346 = list()
listCWE862 = list()

for i in range(0,284):
  CWE79 =0
  CWE327 =0
  CWE502 =0 
  CWE91 =0 
  CWE22 =0 
  CWE835 =0 
  CWE20 =0 
  CWE74 =0 
  CWE200 =0 
  CWE94  =0 
  CWE611  =0
  CWE352  =0
  CWE287  =0
  CWE362  =0
  CWE190  =0
  CWE755  =0
  CWE347  =0
  CWE338  =0
  CWE770  =0
  CWE284  =0
  CWE798  =0
  CWE89   =0
  CWE434  =0
  CWE538  =0
  CWE759  =0
  CWE379  =0
  CWE428  =0
  CWE863  =0
  CWE915  =0
  CWE203  =0
  CWE732  =0
  CWE326  =0
  CWE269  =0
  CWE119 =0 
  CWE918  =0
  CWE295  =0
  CWE78  =0 
  CWE346  =0
  CWE862 =0
  tList= df6.iloc[i].tolist()
  print(tList)
  
  if tList[4] == 'CWE-79':
    CWE79 += 5*tList[2]
  elif tList[4] == 'CWE-327':
    CWE327 += 5*tList[2]
  elif tList[4] == 'CWE-502':
    CWE502 += 5*tList[2]
  elif tList[4] == 'CWE-91':
    CWE91 += 5*tList[2]
  elif tList[4] == 'CWE-22':
    CWE22 += 5*tList[2]
  elif tList[4] == 'CWE-835':
    CWE835 += 5*tList[2]
  elif tList[4] == 'CWE-20':
    CWE20 += 5*tList[2]
  elif tList[4] == 'CWE-74':
    CWE74 += 5*tList[2]
  elif tList[4] == 'CWE-94':
    CWE94 += 5*tList[2]
  elif tList[4] == 'CWE-611':
    CWE611 += 5*tList[2]
  elif tList[4] == 'CWE-352':
    CWE352 += 5*tList[2]
  elif tList[4] == 'CWE-287':
    CWE287 += 5*tList[2]
  elif tList[4] == 'CWE-362':
    CWE362 += 5*tList[2]
  elif tList[4] == 'CWE-502':
    CWE502 += 5*tList[2]
  elif tList[4] == 'CWE-190':
    CWE190 += 5*tList[2]
  elif tList[4] == 'CWE-755':
    CWE755 += 5*tList[2]
  elif tList[4] == 'CWE-347':
    CWE347 += 5*tList[2]
  elif tList[4] == 'CWE-338':
    CWE338 += 5*tList[2]
  elif tList[4] == 'CWE-770':
    CWE770 += 5*tList[2]
  elif tList[4] == 'CWE-284':
    CWE284 += 5*tList[2]
  elif tList[4] == 'CWE-798':
    CWE798 += 5*tList[2]
  elif tList[4] == 'CWE-89':
    CWE89 += 5*tList[2]
  elif tList[4] == 'CWE-434':
    CWE434 += 5*tList[2]
  elif tList[4] == 'CWE-538':
    CWE538 += 5*tList[2]
  elif tList[4] == 'CWE-759':
    CWE759 += 5*tList[2]
  elif tList[4] == 'CWE-379':
    CWE379 += 5*tList[2]
  elif tList[4] == 'CWE-428':
    CWE428 += 5*tList[2]
  elif tList[4] == 'CWE-863':
    CWE863 += 5*tList[2]
  elif tList[4] == 'CWE-915':
    CWE915 += 5*tList[2]
  elif tList[4] == 'CWE-203':
    CWE203 += 5*tList[2]
  elif tList[4] == 'CWE-732':
    CWE732 += 5*tList[2]
  elif tList[4] == 'CWE-326':
    CWE326 += 5*tList[2]
  elif tList[4] == 'CWE-269':
    CWE269 += 5*tList[2]
  elif tList[4] == 'CWE-119':
    CWE119 += 5*tList[2]
  elif tList[4] == 'CWE-918':
    CWE918 += 5*tList[2]
  elif tList[4] == 'CWE-295':
    CWE295 += 5*tList[2]
  elif tList[4] == 'CWE-78':
    CWE78 += 5*tList[2]
  elif tList[4] == 'CWE-346':
    CWE346 += 5*tList[2]
  elif tList[4] == 'CWE-862':
    CWE862 += 5*tList[2]


  if tList[7] == 'CWE-79':
      CWE79 += 4*tList[5]
  elif tList[7] == 'CWE-327':
    CWE327 += 4*tList[5]
  elif tList[7] == 'CWE-502':
    CWE502 += 4*tList[5]
  elif tList[7] == 'CWE-91':
    CWE91 += 4*tList[5]
  elif tList[7] == 'CWE-22':
    CWE22 += 4*tList[5]
  elif tList[7] == 'CWE-835':
    CWE835 += 4*tList[5]
  elif tList[7] == 'CWE-20':
    CWE20 += 4*tList[5]
  elif tList[7] == 'CWE-74':
    CWE74 += 4*tList[5]
  elif tList[7] == 'CWE-94':
    CWE94 += 4*tList[5]
  elif tList[7] == 'CWE-611':
    CWE611 += 4*tList[5]
  elif tList[7] == 'CWE-352':
    CWE352 += 4*tList[5]
  elif tList[7] == 'CWE-287':
    CWE287 += 4*tList[5]
  elif tList[7] == 'CWE-362':
    CWE362 += 4*tList[5]
  elif tList[7] == 'CWE-502':
    CWE502 += 4*tList[5]
  elif tList[7] == 'CWE-190':
    CWE190 += 4*tList[5]
  elif tList[7] == 'CWE-755':
    CWE755 += 4*tList[5]
  elif tList[7] == 'CWE-347':
    CWE347 += 4*tList[5]
  elif tList[7] == 'CWE-338':
    CWE338 += 4*tList[5]
  elif tList[7] == 'CWE-770':
    CWE770 += 4*tList[5]
  elif tList[7] == 'CWE-284':
    CWE284 += 4*tList[5]
  elif tList[7] == 'CWE-798':
    CWE798 += 4*tList[5]
  elif tList[7] == 'CWE-89':
    CWE89 += 4*tList[5]
  elif tList[7] == 'CWE-434':
    CWE434 += 4*tList[5]
  elif tList[7] == 'CWE-538':
    CWE538 += 4*tList[5]
  elif tList[7] == 'CWE-759':
    CWE759 += 4*tList[5]
  elif tList[7] == 'CWE-379':
    CWE379 += 4*tList[5]
  elif tList[7] == 'CWE-428':
    CWE428 += 4*tList[5]
  elif tList[7] == 'CWE-863':
    CWE863 += 4*tList[5]
  elif tList[7] == 'CWE-915':
    CWE915 += 4*tList[5]
  elif tList[7] == 'CWE-203':
    CWE203 += 4*tList[5]
  elif tList[7] == 'CWE-732':
    CWE732 += 4*tList[5]
  elif tList[7] == 'CWE-326':
    CWE326 += 4*tList[5]
  elif tList[7] == 'CWE-269':
    CWE269 += 4*tList[5]
  elif tList[7] == 'CWE-119':
    CWE119 += 4*tList[5]
  elif tList[7] == 'CWE-918':
    CWE918 += 4*tList[5]
  elif tList[7] == 'CWE-295':
    CWE295 += 4*tList[5]
  elif tList[7] == 'CWE-78':
    CWE78 += 4*tList[5]
  elif tList[7] == 'CWE-346':
    CWE346 += 4*tList[5]
  elif tList[7] == 'CWE-862':
    CWE862 += 4*tList[5]


  if tList[10] == 'CWE-79':
      CWE79 += 3*tList[8]
  elif tList[10] == 'CWE-327':
    CWE327 += 3*tList[8]
  elif tList[10] == 'CWE-502':
    CWE502 += 3*tList[8]
  elif tList[10] == 'CWE-91':
    CWE91 += 3*tList[8]
  elif tList[10] == 'CWE-22':
    CWE22 += 3*tList[8]
  elif tList[10] == 'CWE-835':
    CWE835 += 3*tList[8]
  elif tList[10] == 'CWE-20':
    CWE20 += 3*tList[8]
  elif tList[10] == 'CWE-74':
    CWE74 += 3*tList[8]
  elif tList[10] == 'CWE-94':
    CWE94 += 3*tList[8]
  elif tList[10] == 'CWE-611':
    CWE611 += 3*tList[8]
  elif tList[10] == 'CWE-352':
    CWE352 += 3*tList[8]
  elif tList[10] == 'CWE-287':
    CWE287 += 3*tList[8]
  elif tList[10] == 'CWE-362':
    CWE362 += 3*tList[8]
  elif tList[10] == 'CWE-502':
    CWE502 += 3*tList[8]
  elif tList[10] == 'CWE-190':
    CWE190 += 3*tList[8]
  elif tList[10] == 'CWE-755':
    CWE755 += 3*tList[8]
  elif tList[10] == 'CWE-347':
    CWE347 += 3*tList[8]
  elif tList[10] == 'CWE-338':
    CWE338 += 3*tList[8]
  elif tList[10] == 'CWE-770':
    CWE770 += 3*tList[8]
  elif tList[10] == 'CWE-284':
    CWE284 += 3*tList[8]
  elif tList[10] == 'CWE-798':
    CWE798 += 3*tList[8]
  elif tList[10] == 'CWE-89':
    CWE89 += 3*tList[8]
  elif tList[10] == 'CWE-434':
    CWE434 += 3*tList[8]
  elif tList[10] == 'CWE-538':
    CWE538 += 3*tList[8]
  elif tList[10] == 'CWE-759':
    CWE759 += 3*tList[8]
  elif tList[10] == 'CWE-379':
    CWE379 += 3*tList[8]
  elif tList[10] == 'CWE-428':
    CWE428 += 3*tList[8]
  elif tList[10] == 'CWE-863':
    CWE863 += 3*tList[8]
  elif tList[10] == 'CWE-915':
    CWE915 += 3*tList[8]
  elif tList[10] == 'CWE-203':
    CWE203 += 3*tList[8]
  elif tList[10] == 'CWE-732':
    CWE732 += 3*tList[8]
  elif tList[10] == 'CWE-326':
    CWE326 += 3*tList[8]
  elif tList[10] == 'CWE-269':
    CWE269 += 3*tList[8]
  elif tList[10] == 'CWE-119':
    CWE119 += 3*tList[8]
  elif tList[10] == 'CWE-918':
    CWE918 += 3*tList[8]
  elif tList[10] == 'CWE-295':
    CWE295 += 3*tList[8]
  elif tList[10] == 'CWE-78':
    CWE78 += 3*tList[8]
  elif tList[10] == 'CWE-346':
    CWE346 += 3*tList[8]
  elif tList[10] == 'CWE-862':
    CWE862 += 3*tList[8]
  '''
  if tList[13] == 'CWE-79':
      CWE79 += 2*tList[11]
  elif tList[13] == 'CWE-327':
    CWE327 += 2*tList[11]
  elif tList[13] == 'CWE-502':
    CWE502 += 2*tList[11]
  elif tList[13] == 'CWE-91':
    CWE91 += 2*tList[11]
  elif tList[13] == 'CWE-22':
    CWE22 += 2*tList[11]
  elif tList[13] == 'CWE-835':
    CWE835 += 2*tList[11]
  elif tList[13] == 'CWE-20':
    CWE20 += 2*tList[11]
  elif tList[13] == 'CWE-74':
    CWE74 += 2*tList[11]
  elif tList[13] == 'CWE-94':
    CWE94 += 2*tList[11]
  elif tList[13] == 'CWE-611':
    CWE611 += 2*tList[11]
  elif tList[13] == 'CWE-352':
    CWE352 += 2*tList[11]
  elif tList[13] == 'CWE-287':
    CWE287 += 2*tList[11]
  elif tList[13] == 'CWE-362':
    CWE362 += 2*tList[11]
  elif tList[13] == 'CWE-502':
    CWE502 += 2*tList[11]
  elif tList[13] == 'CWE-190':
    CWE190 += 2*tList[11]
  elif tList[13] == 'CWE-755':
    CWE755 += 2*tList[11]
  elif tList[13] == 'CWE-347':
    CWE347 += 2*tList[11]
  elif tList[13] == 'CWE-338':
    CWE338 += 2*tList[11]
  elif tList[13] == 'CWE-770':
    CWE770 += 2*tList[11]
  elif tList[13] == 'CWE-284':
    CWE284 += 2*tList[11]
  elif tList[13] == 'CWE-798':
    CWE798 += 2*tList[11]
  elif tList[13] == 'CWE-89':
    CWE89 += 2*tList[11]
  elif tList[13] == 'CWE-434':
    CWE434 += 2*tList[11]
  elif tList[13] == 'CWE-538':
    CWE538 += 2*tList[11]
  elif tList[13] == 'CWE-759':
    CWE759 += 2*tList[11]
  elif tList[13] == 'CWE-379':
    CWE379 += 2*tList[11]
  elif tList[13] == 'CWE-428':
    CWE428 += 2*tList[11]
  elif tList[13] == 'CWE-863':
    CWE863 += 2*tList[11]
  elif tList[13] == 'CWE-915':
    CWE915 += 2*tList[11]
  elif tList[13] == 'CWE-203':
    CWE203 += 2*tList[11]
  elif tList[13] == 'CWE-732':
    CWE732 += 2*tList[11]
  elif tList[13] == 'CWE-326':
    CWE326 += 2*tList[11]
  elif tList[13] == 'CWE-269':
    CWE269 += 2*tList[11]
  elif tList[13] == 'CWE-119':
    CWE119 += 2*tList[11]
  elif tList[13] == 'CWE-918':
    CWE918 += 2*tList[11]
  elif tList[13] == 'CWE-295':
    CWE295 += 2*tList[11]
  elif tList[13] == 'CWE-78':
    CWE78 += 2*tList[11]
  elif tList[13] == 'CWE-346':
    CWE346 += 2*tList[11]
  elif tList[13] == 'CWE-862':
    CWE862 += 2*tList[11]


  if tList[16] == 'CWE-79':
      CWE79 += 1*tList[14]
  elif tList[16] == 'CWE-327':
    CWE327 += 1*tList[14]
  elif tList[16] == 'CWE-502':
    CWE502 += 1*tList[14]
  elif tList[16] == 'CWE-91':
    CWE91 += 1*tList[14]
  elif tList[16] == 'CWE-22':
    CWE22 += 1*tList[14]
  elif tList[16] == 'CWE-835':
    CWE835 += 1*tList[14]
  elif tList[16] == 'CWE-20':
    CWE20 += 1*tList[14]
  elif tList[16] == 'CWE-74':
    CWE74 += 1*tList[14]
  elif tList[16] == 'CWE-94':
    CWE94 += 1*tList[14]
  elif tList[16] == 'CWE-611':
    CWE611 += 1*tList[14]
  elif tList[16] == 'CWE-352':
    CWE352 += 1*tList[14]
  elif tList[16] == 'CWE-287':
    CWE287 += 1*tList[14]
  elif tList[16] == 'CWE-362':
    CWE362 += 1*tList[14]
  elif tList[16] == 'CWE-502':
    CWE502 += 1*tList[14]
  elif tList[16] == 'CWE-190':
    CWE190 += 1*tList[14]
  elif tList[16] == 'CWE-755':
    CWE755 += 1*tList[14]
  elif tList[16] == 'CWE-347':
    CWE347 += 1*tList[14]
  elif tList[16] == 'CWE-338':
    CWE338 += 1*tList[14]
  elif tList[16] == 'CWE-770':
    CWE770 += 1*tList[14]
  elif tList[16] == 'CWE-284':
    CWE284 += 1*tList[14]
  elif tList[16] == 'CWE-798':
    CWE798 += 1*tList[14]
  elif tList[16] == 'CWE-89':
    CWE89 += 1*tList[14]
  elif tList[16] == 'CWE-434':
    CWE434 += 1*tList[14]
  elif tList[16] == 'CWE-538':
    CWE538 += 1*tList[14]
  elif tList[16] == 'CWE-759':
    CWE759 += 1*tList[14]
  elif tList[16] == 'CWE-379':
    CWE379 += 1*tList[14]
  elif tList[16] == 'CWE-428':
    CWE428 += 1*tList[14]
  elif tList[16] == 'CWE-863':
    CWE863 += 1*tList[14]
  elif tList[16] == 'CWE-915':
    CWE915 += 1*tList[14]
  elif tList[16] == 'CWE-203':
    CWE203 += 1*tList[14]
  elif tList[16] == 'CWE-732':
    CWE732 += 1*tList[14]
  elif tList[16] == 'CWE-326':
    CWE326 += 1*tList[14]
  elif tList[16] == 'CWE-269':
    CWE269 += 1*tList[14]
  elif tList[16] == 'CWE-119':
    CWE119 += 1*tList[14]
  elif tList[16] == 'CWE-918':
    CWE918 += 1*tList[14]
  elif tList[16] == 'CWE-295':
    CWE295 += 1*tList[14]
  elif tList[16] == 'CWE-78':
    CWE78 += 1*tList[14]
  elif tList[16] == 'CWE-346':
    CWE346 += 1*tList[14]
  elif tList[16] == 'CWE-862':
    CWE862 += 1*tList[14]
  '''
  listCWE79.append(CWE79)
  listCWE327.append(CWE327)
  listCWE502.append(CWE502)
  listCWE91.append(CWE91)
  listCWE22.append(CWE22)
  listCWE835.append(CWE835)
  listCWE20.append(CWE20 )
  listCWE74.append(CWE74)
  listCWE200.append(CWE200)
  listCWE94.append(CWE94)
  listCWE611.append(CWE611)
  listCWE352.append(CWE352)
  listCWE287.append(CWE287)
  listCWE362.append(CWE362)
  listCWE190.append(CWE190)
  listCWE755.append(CWE755)
  listCWE347.append(CWE347)
  listCWE338.append(CWE338)
  listCWE770.append(CWE770)
  listCWE284.append(CWE284)
  listCWE798.append(CWE798)
  listCWE89.append(CWE89)
  listCWE434.append(CWE434)
  listCWE538.append(CWE538)
  listCWE759.append(CWE759)
  listCWE379.append(CWE379)
  listCWE428.append(CWE428)
  listCWE863.append(CWE863)
  listCWE915.append(CWE915)
  listCWE203.append(CWE203)
  listCWE732.append(CWE732)
  listCWE326.append(CWE326)
  listCWE269.append(CWE269)
  listCWE119.append(CWE119)
  listCWE918.append(CWE918)
  listCWE295.append(CWE295)
  listCWE78.append(CWE78)
  listCWE346.append(CWE346)
  listCWE862.append(CWE862)
  print(CWE79)
  print(CWE327) 
  print(CWE502) 
  print(CWE91) 
  print(CWE22) 
  print(CWE835) 
  print(CWE20) 
  print(CWE74) 
  print(CWE200) 
  print(CWE94) 
  print(CWE611) 
  print(CWE352) 
  print(CWE287) 
  print(CWE362) 
  print(CWE190) 
  print(CWE755) 
  print(CWE347) 
  print(CWE338) 
  print(CWE770) 
  print(CWE284) 
  print(CWE798) 
  print(CWE89) 
  print(CWE434) 
  print(CWE538) 
  print(CWE759) 
  print(CWE379) 
  print(CWE428) 
  print(CWE863) 
  print(CWE915) 
  print(CWE203) 
  print(CWE732) 
  print(CWE326) 
  print(CWE269) 
  print(CWE119) 
  print(CWE918) 
  print(CWE295) 
  print(CWE78) 
  print(CWE346) 
  print(CWE862)

In [ ]:
print(listCWE79)

[2.836711213564189, 3.5458890169552366, 0, 0, 0, 0, 0, 0, 0, 0, 1.263438831996984, 0, 0, 1.663062011487352, 0, 4.381121424112077, 0, 0, 1.1651013963128536, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 2.9638803814380834, 0, 7.637163701389811, 0, 0, 0, 0, 0, 2.1726703967510694, 1.8449479997174159, 0.6250384180730738, 1.8457032017860249, 0.1910402154934447, 0, 0, 0.2764677437877294, 0, 0.2530091902921837, 0, 1.3626941724042874, 0.2530091902921837, 1.510192996349814, 0.2661596970721016, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.5299733792885761, 0, 0, 0, 0, 0, 0, 0, 0, 1.8584940286334393, 0, 0, 1.8457710445011148, 0, 0, 0, 0.2616789191243789, 0, 0, 0, 0, 0.2981827647384227, 0, 0, 0, 0, 0, 1.2882468291045734, 0, 0, 0.2128303040507319, 1.6167102616346953, 0.3693267801474202, 2.4032479367719803, 0, 0, 0, 2.347769418357789, 1.4480212754861608, 1.3129816810170984, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.9024906308467349, 0, 0, 9.94542651782454, 9.94542651782454, 9.94542651782454, 3.076969970515167, 1.5002717993003247, 0, 0, 0, 0, 0.6010174368228519, 0, 0, 0, 0, 0, 0, 0, 0, 1.4883434873770651, 0.3344626059740043, 0, 1.2956763995212126, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.8868838177162837, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.216760556785038, 0, 0, 0, 0, 0, 0, 0, 0, 0.9332312249116181, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0.8196118887763639, 0, 0, 5.138151977949887, 7.770545639775805, 7.448726406362715, 3.5544939800378783, 3.277174094356717, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1.2257215431943895, 0.5412335763090296, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [ ]:
df6[19]=listCWE79
df6[20] = listCWE327
df6[21]=listCWE502
df6[22] = listCWE91
df6[23]=listCWE22
df6[24] = listCWE835
df6[25]=listCWE20
df6[26] = listCWE74
df6[27]=listCWE200
df6[28] = listCWE200
df6[29]=listCWE611
df6[30] = listCWE352
df6[31]=listCWE287
df6[32] = listCWE362
df6[33]=listCWE190
df6[34] = listCWE755
df6[35]=listCWE347
df6[36] = listCWE338
df6[37]=listCWE770
df6[38] = listCWE284
df6[39]=listCWE798
df6[40] = listCWE89
df6[41]=listCWE434
df6[42] = listCWE538
df6[43]=listCWE759
df6[44] = listCWE379
df6[45]=listCWE428
df6[46] = listCWE863
df6[47]=listCWE915
df6[48] = listCWE203
df6[49]=listCWE732
df6[50] = listCWE326
df6[51]=listCWE269
df6[52] = listCWE119
df6[53] = listCWE918
df6[54]=listCWE295
df6[55] = listCWE78
df6[56]=listCWE346
df6[57] = listCWE862

In [ ]:
df6

,0,1,2,3,4,5,6,7,8,9,...,48,49,50,51,52,53,54,55,56,57
0,0,CWE-79,0.969017,43,CWE-352,0.709178,1,CWE-79,0.509991,73,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
1,1,CWE-79,0.709178,0,CWE-79,0.698019,43,CWE-352,0.379888,73,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
2,2,CWE-79,0.724223,49,CWE-352,0.615234,52,CWE-352,0.614983,50,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
3,3,CWE-327,0.211456,248,CWE-78,0.206611,143,CWE-502,0.205309,62,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,1.057278,0.000000,0.0
4,4,CWE-327,0.277508,132,CWE-91,0.241131,131,CWE-91,0.229998,133,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
279,279,CWE-862,0.288656,62,CWE-362,0.275619,90,CWE-347,0.260459,41,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
280,280,CWE-732,0.319783,171,CWE-379,0.256628,167,CWE-379,0.250705,168,...,0.0,0.000000,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
281,281,CWE-732,0.374063,282,CWE-732,0.346804,283,CWE-732,0.334914,7,...,0.0,3.257527,0.0,0.0,0.0,0.0,0.0,0.000000,0.000000,0.0
282,282,CWE-732,0.900648,283,CWE-732,0.374063,281,CWE-732,0.253221,255,...,0.0,5.999490,0.0,0.0,0.0,0.0,0.0,0.000000,0.759662,0.0
283,283,CWE-732,0.900648,282,CWE-732,0.346804,281,CWE-732,0.253576,255,...,0.0,5.890454,0.0,0.0,0.0,0.0,0.0,0.000000,0.760727,0.0

In [ ]:
df6.to_excel("result5.xlsx")

In [ ]:
import pandas as pd

bad = pd.read_csv('uniqueBadEmbeddings.txt', sep=" ", header=None)

In [ ]:
import pandas as pd

good = pd.read_csv('uniqueGoodEmbeddings.txt', sep=" ", header=None)

In [ ]:
bad

In [ ]:
good

,0,1,2,3,4,5,6,7,8,9,...,374,375,376,377,378,379,380,381,382,383
0,-0.732726,0.392508,-0.008045,0.669277,0.533917,0.593041,-0.102830,0.563711,-0.131963,0.215237,...,0.561083,-0.073520,0.767213,0.077291,0.635481,0.648587,-0.129466,-0.164602,0.652976,0.732340
1,-0.732129,0.291026,-0.009033,-0.882865,-0.740211,-0.031823,0.287497,-0.511272,0.497846,0.468543,...,0.122902,0.267092,-0.087674,-0.409174,0.515987,0.767836,-0.171771,0.415997,-0.115875,0.208258
2,-0.596533,0.253458,-0.030266,-0.774413,-0.862819,-0.131625,0.362806,-0.414045,0.408064,0.381814,...,0.136150,0.254798,0.089549,-0.504064,0.632264,0.875923,0.051790,0.468571,0.059374,0.190778
3,-0.593607,0.136625,-0.016376,-0.364444,-0.882267,-0.277917,0.290539,-0.111157,-0.105166,0.547506,...,0.081887,-0.070993,-0.206238,0.166726,0.076867,-0.233796,-0.177818,0.480995,0.295565,-0.004673
4,-0.074118,-0.354940,-0.360811,-0.134348,-0.075128,0.109613,-0.050365,-0.570681,-0.001387,0.621436,...,-0.248912,0.469327,0.109813,-0.097891,-0.057586,0.557535,-0.112165,0.462844,0.180632,0.654061
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,-0.357599,0.883179,0.464533,0.107315,-0.425418,-0.108157,0.298638,0.097083,-0.350709,0.170185,...,0.125196,-0.438409,-0.197691,-0.429472,0.397007,-0.329466,-0.425173,0.087122,-0.435507,0.768832
605,0.530472,0.272354,0.742727,0.108121,-0.247388,-0.671771,0.245436,-0.317131,0.386791,0.383422,...,-0.456503,-0.088406,-0.456922,-0.099172,-0.618452,-0.089200,0.339585,0.081154,-0.090740,0.463197
606,0.819608,0.631838,0.589474,0.585027,0.515516,0.336110,0.734999,-0.618000,0.528983,0.605285,...,0.293940,0.631409,-0.397440,-0.830730,-0.429265,0.494758,-0.839601,0.156755,0.044915,0.105548
607,0.701982,0.452611,0.244194,-0.255049,-0.581379,-0.750640,0.463572,-0.201788,-0.208766,-0.207034,...,-0.650331,0.436460,-0.694856,-0.068432,0.604262,-0.874903,-0.242996,-0.354128,-0.292422,-0.114144
608,-0.300350,0.052744,-0.018330,-0.102489,0.023285,-0.020837,-0.389641,-0.260586,-0.383283,0.248464,...,0.057544,0.097754,0.120662,0.564899,-0.299158,-0.500626,0.131365,-0.328117,-0.211503,-0.411279

In [ ]:

listBad = list()
for i in range(0,284):
  listBad.append('Bad')

In [ ]:
listGood = list()
for i in range(0,609):
  listGood.append('Good')

In [ ]:
listGood

[]

In [ ]:
bad[384] = listBad

In [ ]:
good[384] = listGood

In [ ]:
len(listBad)

568

In [ ]:
good

,0,1,2,3,4,5,6,7,8,9,...,375,376,377,378,379,380,381,382,383,384
0,-0.732726,0.392508,-0.008045,0.669277,0.533917,0.593041,-0.102830,0.563711,-0.131963,0.215237,...,-0.073520,0.767213,0.077291,0.635481,0.648587,-0.129466,-0.164602,0.652976,0.732340,Good
1,-0.732129,0.291026,-0.009033,-0.882865,-0.740211,-0.031823,0.287497,-0.511272,0.497846,0.468543,...,0.267092,-0.087674,-0.409174,0.515987,0.767836,-0.171771,0.415997,-0.115875,0.208258,Good
2,-0.596533,0.253458,-0.030266,-0.774413,-0.862819,-0.131625,0.362806,-0.414045,0.408064,0.381814,...,0.254798,0.089549,-0.504064,0.632264,0.875923,0.051790,0.468571,0.059374,0.190778,Good
3,-0.593607,0.136625,-0.016376,-0.364444,-0.882267,-0.277917,0.290539,-0.111157,-0.105166,0.547506,...,-0.070993,-0.206238,0.166726,0.076867,-0.233796,-0.177818,0.480995,0.295565,-0.004673,Good
4,-0.074118,-0.354940,-0.360811,-0.134348,-0.075128,0.109613,-0.050365,-0.570681,-0.001387,0.621436,...,0.469327,0.109813,-0.097891,-0.057586,0.557535,-0.112165,0.462844,0.180632,0.654061,Good
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
604,-0.357599,0.883179,0.464533,0.107315,-0.425418,-0.108157,0.298638,0.097083,-0.350709,0.170185,...,-0.438409,-0.197691,-0.429472,0.397007,-0.329466,-0.425173,0.087122,-0.435507,0.768832,Good
605,0.530472,0.272354,0.742727,0.108121,-0.247388,-0.671771,0.245436,-0.317131,0.386791,0.383422,...,-0.088406,-0.456922,-0.099172,-0.618452,-0.089200,0.339585,0.081154,-0.090740,0.463197,Good
606,0.819608,0.631838,0.589474,0.585027,0.515516,0.336110,0.734999,-0.618000,0.528983,0.605285,...,0.631409,-0.397440,-0.830730,-0.429265,0.494758,-0.839601,0.156755,0.044915,0.105548,Good
607,0.701982,0.452611,0.244194,-0.255049,-0.581379,-0.750640,0.463572,-0.201788,-0.208766,-0.207034,...,0.436460,-0.694856,-0.068432,0.604262,-0.874903,-0.242996,-0.354128,-0.292422,-0.114144,Good
608,-0.300350,0.052744,-0.018330,-0.102489,0.023285,-0.020837,-0.389641,-0.260586,-0.383283,0.248464,...,0.097754,0.120662,0.564899,-0.299158,-0.500626,0.131365,-0.328117,-0.211503,-0.411279,Good

In [ ]:
good.to_excel("good.xlsx")

In [ ]:
bad.to_excel("bad.xlsx")

In [ ]:
l = ['CWE-79', 'CWE-327', 'CWE-502', 'CWE-91', 'CWE-22', 'CWE-835',
       'CWE-20', 'CWE-74', 'CWE-200', 'CWE-94', 'CWE-611', 'CWE-352',
       'CWE-287', 'CWE-362', 'CWE-190', 'CWE-755', 'CWE-347', 'CWE-338',
       'CWE-770', 'CWE-284', 'CWE-798', 'CWE-89', 'CWE-434', 'CWE-538',
       'CWE-759', 'CWE-379', 'CWE-428', 'CWE-863', 'CWE-915', 'CWE-203',
       'CWE-732', 'CWE-326', 'CWE-269', 'CWE-119', 'CWE-918', 'CWE-295',
       'CWE-78', 'CWE-346', 'CWE-862']

In [ ]:
from collections import Counter


l1 =Counter(df6[1]).keys()
l2 =Counter(df6[1]).values()
print(Counter(df6[1]).keys()) # equals to list(set(words))
print(Counter(df6[1]).values()) # counts the elements' frequency

dict_keys(['CWE-79', 'CWE-327', 'CWE-502', 'CWE-91', 'CWE-22', 'CWE-835', 'CWE-20', 'CWE-74', 'CWE-200', 'CWE-94', 'CWE-611', 'CWE-352', 'CWE-287', 'CWE-362', 'CWE-190', 'CWE-755', 'CWE-347', 'CWE-338', 'CWE-770', 'CWE-284', 'CWE-798', 'CWE-89', 'CWE-434', 'CWE-538', 'CWE-759', 'CWE-379', 'CWE-428', 'CWE-863', 'CWE-915', 'CWE-203', 'CWE-732', 'CWE-326', 'CWE-269', 'CWE-119', 'CWE-918', 'CWE-295', 'CWE-78', 'CWE-346', 'CWE-862'])
dict_values([21, 4, 11, 8, 16, 1, 18, 34, 13, 3, 24, 18, 9, 3, 2, 1, 4, 2, 4, 1, 3, 4, 1, 1, 3, 5, 1, 5, 1, 1, 30, 5, 2, 4, 2, 4, 5, 8, 2])

In [ ]:
import numpy as np
values, counts = np.unique(df6[1], return_counts=True)

In [ ]:
valuesList = values.tolist()
countsList = counts.tolist()

In [ ]:
valuesList

['CWE-119',
 'CWE-190',
 'CWE-20',
 'CWE-200',
 'CWE-203',
 'CWE-22',
 'CWE-269',
 'CWE-284',
 'CWE-287',
 'CWE-295',
 'CWE-326',
 'CWE-327',
 'CWE-338',
 'CWE-346',
 'CWE-347',
 'CWE-352',
 'CWE-362',
 'CWE-379',
 'CWE-428',
 'CWE-434',
 'CWE-502',
 'CWE-538',
 'CWE-611',
 'CWE-732',
 'CWE-74',
 'CWE-755',
 'CWE-759',
 'CWE-770',
 'CWE-78',
 'CWE-79',
 'CWE-798',
 'CWE-835',
 'CWE-862',
 'CWE-863',
 'CWE-89',
 'CWE-91',
 'CWE-915',
 'CWE-918',
 'CWE-94']

In [ ]:
countsList

In [ ]:
r = pd.DataFrame()

In [ ]:
r[0]= valuesList
r[1] = countsList

In [ ]:
r

          0   1
0   CWE-119   4
1   CWE-190   2
2    CWE-20  18
3   CWE-200  13
4   CWE-203   1
5    CWE-22  16
6   CWE-269   2
7   CWE-284   1
8   CWE-287   9
9   CWE-295   4
10  CWE-326   5
11  CWE-327   4
12  CWE-338   2
13  CWE-346   8
14  CWE-347   4
15  CWE-352  18
16  CWE-362   3
17  CWE-379   5
18  CWE-428   1
19  CWE-434   1
20  CWE-502  11
21  CWE-538   1
22  CWE-611  24
23  CWE-732  30
24   CWE-74  34
25  CWE-755   1
26  CWE-759   3
27  CWE-770   4
28   CWE-78   5
29   CWE-79  21
30  CWE-798   3
31  CWE-835   1
32  CWE-862   2
33  CWE-863   5
34   CWE-89   4
35   CWE-91   8
36  CWE-915   1
37  CWE-918   2
38   CWE-94   3

In [ ]:
r.to_excel("count.xlsx")